{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "JuiceShop2",
    "contact": {}
  },
  "host": "juice-shop.herokuapp.com",
  "basePath": "/",
  "securityDefinitions": {},
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/rest/products/search": {
      "get": {
        "summary": "Search",
        "tags": [
          "Products"
        ],
        "operationId": "Search",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "q",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/rest/products/1/reviews": {
      "get": {
        "summary": "Add Review",
        "tags": [
          "Products"
        ],
        "operationId": "AddReview",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/rest/basket/8": {
      "get": {
        "description": "Retrieve the shopping basket",
        "summary": "Shopping Basket",
        "tags": [
          "Shopping"
        ],
        "operationId": "ShoppingBasket",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/api/Cards": {
      "post": {
        "description": "This request adds new credit card information",
        "summary": "Add Credit Card",
        "tags": [
          "Shopping"
        ],
        "operationId": "AddCreditCard",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddCreditCardRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/api/Users": {
      "post": {
        "description": "This request registers a new user",
        "summary": "Register new user",
        "tags": [
          "Misc"
        ],
        "operationId": "Registernewuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisternewuserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/rest/user/login": {
      "post": {
        "summary": "Login Request",
        "tags": [
          "Misc"
        ],
        "operationId": "LoginRequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequestRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Login-ValidUser"
            },
            "examples": {
              "application/json": {
                "authentication": {
                  "token": "",
                  "bid": 9,
                  "umail": "mary@mary.com"
                }
              }
            },
            "headers": {}
          },
          "401": {
            "description": "Unauthorized",
            "schema": {}
          }
        }
      }
    }
  },
  "definitions": {
    "AddCreditCardRequest": {
      "title": "AddCreditCardRequest",
      "example": {
        "fullName": "maverick",
        "cardNum": 1234567891234567,
        "expMonth": "2",
        "expYear": "2085"
      },
      "type": "object",
      "properties": {
        "fullName": {
          "type": "string"
        },
        "cardNum": {
          "type": "integer",
          "format": "int64"
        },
        "expMonth": {
          "type": "string"
        },
        "expYear": {
          "type": "string"
        }
      },
      "required": [
        "fullName",
        "cardNum",
        "expMonth",
        "expYear"
      ]
    },
    "RegisternewuserRequest": {
      "title": "RegisternewuserRequest",
      "example": {
        "email": "john@john.com",
        "password": "mary123",
        "passwordRepeat": "mary123",
        "securityQuestion": {
          "id": 2,
          "question": "Mother's maiden name?",
          "createdAt": "2020-06-01T03:10:44.683Z",
          "updatedAt": "2020-06-01T03:10:44.683Z"
        },
        "securityAnswer": "mary"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "passwordRepeat": {
          "type": "string"
        },
        "securityQuestion": {
          "$ref": "#/definitions/SecurityQuestion"
        },
        "securityAnswer": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password",
        "passwordRepeat",
        "securityQuestion",
        "securityAnswer"
      ]
    },
    "SecurityQuestion": {
      "title": "SecurityQuestion",
      "example": {
        "id": 2,
        "question": "Mother's maiden name?",
        "createdAt": "2020-06-01T03:10:44.683Z",
        "updatedAt": "2020-06-01T03:10:44.683Z"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "question": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "question",
        "createdAt",
        "updatedAt"
      ]
    },
    "LoginRequestRequest": {
      "title": "LoginRequestRequest",
      "example": {
        "email": "mary@mary.com",
        "password": "wrongpassword"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "Login-ValidUser": {
      "title": "Login-ValidUser",
      "example": {
        "authentication": {
          "token": "",
          "bid": 9,
          "umail": "mary@mary.com"
        }
      },
      "type": "object",
      "properties": {
        "authentication": {
          "$ref": "#/definitions/Authentication"
        }
      },
      "required": [
        "authentication"
      ]
    },
    "Authentication": {
      "title": "Authentication",
      "example": {
        "token": "",
        "bid": 9,
        "umail": "mary@mary.com"
      },
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        },
        "bid": {
          "type": "integer",
          "format": "int32"
        },
        "umail": {
          "type": "string"
        }
      },
      "required": [
        "token",
        "bid",
        "umail"
      ]
    }
  },
  "tags": [
    {
      "name": "Products"
    },
    {
      "name": "Shopping"
    },
    {
      "name": "Misc",
      "description": ""
    }
  ]
}